In [137]:
import pandas as pd
import numpy as np

In [138]:
data = pd.read_csv('Dataset/All_Movies1.csv', lineterminator='\n')

In [139]:
data.head()

,Unnamed: 0.1,Unnamed: 0,Title,Director,Cast,id,genres,imdb_id,original_language,overview,popularity,poster_path,release_date,runtime,title,vote_average,vote_count
0,0,1,Kaun Pravin Tambe?,Jayprad Desai,Shreyas Talpade,946652.0,Drama,tt18568902,hi,Mumbai-born leg-spinner Pravin Tambe made his ...,3.118,/w6t4nzjbmlGDAYnNvUeo6zxMySC.jpg,2022,2 hrs 13 min,Kaun Pravin Tambe?,7.3,10
1,1,2,Cobalt Blue,Sachin Kundalkar,"Prateik Babbar,Neelay Mehendale,Anjali Sivaram...",897097.0,"Romance,Drama",tt15314640,hi,When an aspiring author and his free-spirited ...,5.029,/59CjIDHHvNyiinRwaSIouWnPNrY.jpg,2022,1 hrs 52 min,Cobalt Blue,6.4,18
2,2,3,Dasvi,Tushar Jalota,"Abhishek Bachchan,Yami Gautam,Nimrat Kaur",799713.0,"Drama,Comedy",tt14107554,hi,"Jailed under a tough cop, an uneducated politi...",4.485,/zL40soH0AYoBD5BVNu9U2B98ejD.jpg,2022,2 hrs 7 min,Dasvi,5.4,18
3,3,4,Hurdang,Nikhil Nagesh Bhat,"Sunny Kaushal,Nushrratt Bharuccha,Vijay Varma",809309.0,"Drama,Romance",tt10919304,hi,"In the 1990s' Allahabad, a brash college stude...",3.690,/vcsr4oajxfEMYpjxfgrVfJCbczk.jpg,2022,2 hrs 2 min,Hurdang,5.0,2
4,4,5,Jersey,Gowtam Tinnanuri,"Shahid Kapoor,Mrunal Thakur,Pankaj Kapur",679018.0,Drama,tt5301942,hi,"An ex-cricketer struggling to make ends meet, ...",9.077,/ur2D5MXrwBBymQ7DjG0cOFen2yh.jpg,2022,2 hrs 55 min,Jersey,7.0,31

In [140]:
data = data.loc[:, ['Title', 'Director', 'Cast', 'genres']]

In [141]:
def split_actors(row):
    actors = row.split(',')
    actors = [actor.strip() for actor in actors]
    
    actors += [np.nan] * (3 - len(actors))
    
    return pd.Series(actors[:3], index=['actor_1_name', 'actor_2_name', 'actor_3_name'])

# Apply the function to the DataFrame
data[['actor_1_name', 'actor_2_name', 'actor_3_name']] = data['Cast'].apply(split_actors)

In [142]:
data.drop(columns=['Cast'], inplace=True)

In [143]:
data['genres'] = data['genres'].str.replace(',', ' ')

In [144]:
data = data.rename(columns={'Title':'movie_title'})
data = data.rename(columns={'Director':'director_name'})

In [145]:
data['comb'] = data.apply(
    lambda row: (
        str(row['actor_1_name']) + ' ' + str(row['director_name']) + ' ' + str(row['genres'])
        if pd.isna(row['actor_2_name']) 
        else str(row['actor_1_name']) + ' ' + str(row['actor_2_name']) + ' ' + str(row['actor_3_name']) + ' ' + str(row['director_name']) + ' ' + str(row['genres'])
    ), axis=1
)

In [146]:
data

,movie_title,director_name,genres,actor_1_name,actor_2_name,actor_3_name,comb
0,Kaun Pravin Tambe?,Jayprad Desai,Drama,Shreyas Talpade,NaN,NaN,Shreyas Talpade Jayprad Desai Drama
1,Cobalt Blue,Sachin Kundalkar,Romance Drama,Prateik Babbar,Neelay Mehendale,Anjali Sivaraman,Prateik Babbar Neelay Mehendale Anjali Sivaram...
2,Dasvi,Tushar Jalota,Drama Comedy,Abhishek Bachchan,Yami Gautam,Nimrat Kaur,Abhishek Bachchan Yami Gautam Nimrat Kaur Tush...
3,Hurdang,Nikhil Nagesh Bhat,Drama Romance,Sunny Kaushal,Nushrratt Bharuccha,Vijay Varma,Sunny Kaushal Nushrratt Bharuccha Vijay Varma ...
4,Jersey,Gowtam Tinnanuri,Drama,Shahid Kapoor,Mrunal Thakur,Pankaj Kapur,Shahid Kapoor Mrunal Thakur Pankaj Kapur Gowta...
...,...,...,...,...,...,...,...
3355,Les Misérables,Tom Hooper,History Drama,Hugh Jackman,Russell Crowe,Eddie Redmayne,Hugh Jackman Russell Crowe Eddie Redmayne Tom ...
3356,Parental Guidance,Andy Fickman,Comedy,Billy Crystal,Bette Midler,Marisa Tomei,Billy Crystal Bette Midler Marisa Tomei Andy F...
3357,West of Memphis,Amy J. Berg,Documentary,West Memphis Three,NaN,NaN,West Memphis Three Amy J. Berg Documentary
3358,Quartet,Dustin Hoffman,Drama Comedy Romance,Maggie Smith,Tom Courtenay,Billy Connolly,Maggie Smith Tom Courtenay Billy Connolly Dust...
3359,Promised Land,Gus Van Sant,Drama,Matt Damon,John Krasinski,Rosemarie DeWitt,Matt Damon John Krasinski Rosemarie DeWitt Gus...

In [147]:
data['actor_1_name'] = data['actor_1_name'].replace(np.nan, 'unknown')
data['actor_2_name'] = data['actor_2_name'].replace(np.nan, 'unknown')
data['actor_3_name'] = data['actor_3_name'].replace(np.nan, 'unknown')
data['director_name'] = data['director_name'].replace(np.nan, 'unknown')

In [148]:
data

,movie_title,director_name,genres,actor_1_name,actor_2_name,actor_3_name,comb
0,Kaun Pravin Tambe?,Jayprad Desai,Drama,Shreyas Talpade,unknown,unknown,Shreyas Talpade Jayprad Desai Drama
1,Cobalt Blue,Sachin Kundalkar,Romance Drama,Prateik Babbar,Neelay Mehendale,Anjali Sivaraman,Prateik Babbar Neelay Mehendale Anjali Sivaram...
2,Dasvi,Tushar Jalota,Drama Comedy,Abhishek Bachchan,Yami Gautam,Nimrat Kaur,Abhishek Bachchan Yami Gautam Nimrat Kaur Tush...
3,Hurdang,Nikhil Nagesh Bhat,Drama Romance,Sunny Kaushal,Nushrratt Bharuccha,Vijay Varma,Sunny Kaushal Nushrratt Bharuccha Vijay Varma ...
4,Jersey,Gowtam Tinnanuri,Drama,Shahid Kapoor,Mrunal Thakur,Pankaj Kapur,Shahid Kapoor Mrunal Thakur Pankaj Kapur Gowta...
...,...,...,...,...,...,...,...
3355,Les Misérables,Tom Hooper,History Drama,Hugh Jackman,Russell Crowe,Eddie Redmayne,Hugh Jackman Russell Crowe Eddie Redmayne Tom ...
3356,Parental Guidance,Andy Fickman,Comedy,Billy Crystal,Bette Midler,Marisa Tomei,Billy Crystal Bette Midler Marisa Tomei Andy F...
3357,West of Memphis,Amy J. Berg,Documentary,West Memphis Three,unknown,unknown,West Memphis Three Amy J. Berg Documentary
3358,Quartet,Dustin Hoffman,Drama Comedy Romance,Maggie Smith,Tom Courtenay,Billy Connolly,Maggie Smith Tom Courtenay Billy Connolly Dust...
3359,Promised Land,Gus Van Sant,Drama,Matt Damon,John Krasinski,Rosemarie DeWitt,Matt Damon John Krasinski Rosemarie DeWitt Gus...

In [149]:
data['movie_title'] = data['movie_title'].str.lower()

In [150]:
old = pd.read_csv('new_data.csv')

new_data_1 = pd.concat([old, data])

In [151]:
new_data_1

,movie_title,director_name,actor_1_name,actor_2_name,actor_3_name,genres,comb
0,avatar,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,CCH Pounder Joel David Moore Wes Studi James C...
1,pirates of the caribbean: at world's end,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,spectre,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,the dark knight rises,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,star wars: episode vii - the force awakens ...,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
3355,les misérables,Tom Hooper,Hugh Jackman,Russell Crowe,Eddie Redmayne,History Drama,Hugh Jackman Russell Crowe Eddie Redmayne Tom ...
3356,parental guidance,Andy Fickman,Billy Crystal,Bette Midler,Marisa Tomei,Comedy,Billy Crystal Bette Midler Marisa Tomei Andy F...
3357,west of memphis,Amy J. Berg,West Memphis Three,unknown,unknown,Documentary,West Memphis Three Amy J. Berg Documentary
3358,quartet,Dustin Hoffman,Maggie Smith,Tom Courtenay,Billy Connolly,Drama Comedy Romance,Maggie Smith Tom Courtenay Billy Connolly Dust...
3359,promised land,Gus Van Sant,Matt Damon,John Krasinski,Rosemarie DeWitt,Drama,Matt Damon John Krasinski Rosemarie DeWitt Gus...

In [152]:
new_data_1.drop_duplicates(subset = "movie_title", keep = 'last', inplace = True)

In [153]:
new_data_1

,movie_title,director_name,actor_1_name,actor_2_name,actor_3_name,genres,comb
0,avatar,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,CCH Pounder Joel David Moore Wes Studi James C...
1,pirates of the caribbean: at world's end,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,Johnny Depp Orlando Bloom Jack Davenport Gore ...
4,star wars: episode vii - the force awakens ...,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,Doug Walker Rob Walker unknown Doug Walker Doc...
6,tangled,Nathan Greno,Brad Garrett,Donna Murphy,M.C. Gainey,Adventure Animation Comedy Family Fantasy Musi...,Brad Garrett Donna Murphy M.C. Gainey Nathan G...
8,harry potter and the half-blood prince,David Yates,Alan Rickman,Daniel Radcliffe,Rupert Grint,Adventure Family Fantasy Mystery,Alan Rickman Daniel Radcliffe Rupert Grint Dav...
...,...,...,...,...,...,...,...
3355,les misérables,Tom Hooper,Hugh Jackman,Russell Crowe,Eddie Redmayne,History Drama,Hugh Jackman Russell Crowe Eddie Redmayne Tom ...
3356,parental guidance,Andy Fickman,Billy Crystal,Bette Midler,Marisa Tomei,Comedy,Billy Crystal Bette Midler Marisa Tomei Andy F...
3357,west of memphis,Amy J. Berg,West Memphis Three,unknown,unknown,Documentary,West Memphis Three Amy J. Berg Documentary
3358,quartet,Dustin Hoffman,Maggie Smith,Tom Courtenay,Billy Connolly,Drama Comedy Romance,Maggie Smith Tom Courtenay Billy Connolly Dust...
3359,promised land,Gus Van Sant,Matt Damon,John Krasinski,Rosemarie DeWitt,Drama,Matt Damon John Krasinski Rosemarie DeWitt Gus...

In [154]:
new_data_1.to_csv('movie_data.csv', index=False)